version: "2"

services:
  test-mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - rede-test

  pytest-test:
    image: pytest-test:latest
    ports:
      - "5000:5000"
    networks:
      - rede-test
    links:
      - test-mongo
    depends_on:
      - test-mongo

networks:
  rede-test:
    driver: bridge
