apiVersion: v1
kind: Service
metadata:
  name: aspnet-core-api-example
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: http
  selector:
    app: aspnet-core-api-example
  type: ClusterIP
