pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                echo 'Testing trigger !'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy test'
                sh 'docker run -d -P --name iamfoo containous/whoami'
            }
        }
    }
}
