apiVersion: v1
kind: Service
metadata:
  name: aspnet-core-api-example
spec:
  ports:
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000
  selector:
    app: aspnet-core-api-example
  type: ClusterIP
